apiVersion: v1
kind: Service
metadata:
  name: finbank-service
spec:
  selector:
    app: finbank
  ports:
    - protocol: TCP
      port: 80         # The port users visit
      targetPort: 3001 # The port your Docker container uses
  type: NodePort       # Exposes the service on a port on your Machine (for local testing)