apiVersion: apps/v1
kind: Deployment
metadata:
  name: finbank-deployment
  labels:
    app: finbank
spec:
  replicas: 3
  selector:
    matchLabels:
      app: finbank
  template:
    metadata:
      labels:
        app: finbank
    spec:
      containers:
      - name: finbank-container
        image: docker.io/vipuljain675/finbank-os:32940c0
        imagePullPolicy: Always # ðŸ‘ˆ Ensures K8s always checks for new content
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: finbank-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: finbank-secrets
              key: JWT_SECRET